# install.packages(c("R6", "BBmisc", "stringr", "tidyverse", "rlist", "mgcv", "mvtnorm", "data.table",
#                    "dplyr", "ggplot2", "ggpubr", "batchtools", "glmnet", "quantreg", "splines",
#                    "partitions", "partykit", "checkmate", "mlr3", "mlr3learners", "mlr3measures",
#                    "mlr3pipelines", "mlr3tuning", "caTools", "igraph", "fossil", "kableExtra))

library(R6)
library(BBmisc)
library(stringr)
library(tidyverse)
library(rlist)
library(mgcv)
library(mvtnorm)
library(data.table)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(glmnet)
library(quantreg)
library(splines)
library(partitions)
library(partykit)
library(checkmate)
library(mlr3)
library(mlr3learners)
library(mlr3measures)
library(mlr3pipelines)
library(mlr3tuning)
library(caTools)
library(igraph)
library(batchtools)
library(fossil)
library(kableExtra)
library(GGally)
